name: Fredi Bach
favicon: null
layout_spectrum: 0.3250323738902807
typography_spectrum: 0.7701206814963371
title: 'Paragliding XC Pilot & Frontend Engineer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3713477491401136
  lightness: 0.2826314843259752
  saturation: 0.46220747218467295
  rhythmicContrast: 0.9850519949104637
purpose: []
